### ISSUE TITLE
Gaya Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [AlfazaSatria/search-text-onvideo-vuejs#2]
Hi Mas Satria, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Satria.

Mas juga sudah menggunakan kerangka kerja CSS Bootstrap untuk memberikan gaya pada aplikasi pencari teks pada videonya. Namun, saya ada satu saran kecil Mas terkait gaya penulisan kode:

Saya ambil contoh pada berkas `index.html` baris ke 19 berikut:

https://github.com/AlfazaSatria/search-text-onvideo-vuejs/blob/b7738bdd90000ac8e2ccebaeb9931db4643271ad/index.html#L19

Akan lebih baik jika Mas menambahkan spasi antara `{{` dan `}}` sehingga kode tersebut kurang lebih akan menjadi:

```html
<h1>{{ header }}</h1>
```

Lebih lanjut Mas dapat membaca mengenai gaya penulisan kode pada Vue.js pada tautan berikut, [Dokumentasi Vue.js Indonesia - Gaya Penuisaan](https://docs.vuejs.id/v2/style-guide/)

Walaupun terlihat sepeleh, namun menurut saya akan sangat berguna Mas untuk kedepannya nanti. Apalagi jika sudah bekerja dalam tim, bahkan terkadang kita bisa menganggap kalau kode tersebut seperti ditulis oleh satu orang saja karena keseragaman gaya penulisannya.

Selain itu pada berkas `readme.md`, Mas menyebutkan proyek ini menggunakan Vue 4.4.6 sedangkan Vue.js sendiri sekarang masih versi [2.6.11](https://github.com/vuejs/vue/releases) Mas.

Semangat Mas! 😄

**Comment by AlfazaSatria** [comment]
Terima kasih atas feedbacknya mas.
